/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ivan
 */

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

public class ConsultarUsuariosC extends javax.swing.JInternalFrame {

    /**
     * Creates new form ConsultarUsuariosC
     */
    public ConsultarUsuariosC() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        opConsultaTotalUsuarios = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CONSULTA TOTAL DE CUENTAS");

        opConsultaTotalUsuarios.setText("CONSULTA");
        opConsultaTotalUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opConsultaTotalUsuariosActionPerformed(evt);
            }
        });

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "USUARIO", "OFERTA/DEMANDA", "CUENTA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Tabla);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(opConsultaTotalUsuarios))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 861, Short.MAX_VALUE)))
                .addGap(133, 133, 133))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(opConsultaTotalUsuarios))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
                .addGap(214, 214, 214))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opConsultaTotalUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opConsultaTotalUsuariosActionPerformed
        // TODO add your handling code here:
        // Declaración de las variables para la Base de Datos
        Connection conexion;
        Statement sentencia;
        ResultSet resultado;
        System.out.println( "Iniciando opcion de consulta de usuarios." );
        // Se carga el driver JDBC-ODBC
        try {
        Class.forName( "com.mysql.jdbc.Driver" );
        } catch( ClassNotFoundException e ) {
        System.out.println( "No se pudo cargar el puente JDBC-ODBC." );
        return;
        }
        try {
        // Se establece la conexión con la base de datos
        conexion = DriverManager.getConnection(
        "jdbc:mysql://db4free.net:3306/kmijapp","jefe21054","operahotspring123" );
        sentencia = conexion.createStatement();
        // Se realiza la consulta de la tabla USUARIOS
        resultado = sentencia.executeQuery( "SELECT * FROM USUARIO, CUENTA"
        +" WHERE CUENTA.USUARIO_id = USUARIO.id AND CUENTA.activa = 'SI'");
        // Declaración de la variable para la Tabla
        DefaultTableModel ModeloTabla;
        String [] columnas = {"ID","USUARIO","OFERTA/DEMANDA","SERVICIO"};
        String [] registro = new String[4];
        ModeloTabla = new DefaultTableModel(null,columnas);
        while (resultado.next()){
        registro[0]=resultado.getString("USUARIO.id");
        registro[1]=resultado.getString("USUARIO.user");
        registro[2]=resultado.getString("USUARIO.servicio");
        registro[3]=resultado.getString("CUENTA.servicio");
        ModeloTabla.addRow(registro);
        }
        Tabla.setModel(ModeloTabla);
        sentencia.close();
        } catch( SQLException e ) {
        System.out.println( e );
        }
    }//GEN-LAST:event_opConsultaTotalUsuariosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton opConsultaTotalUsuarios;
    // End of variables declaration//GEN-END:variables
}
