
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ivan
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        // JFrame adquiriendo el tamaño de pantalla completa o FullScreen
        this.setTitle("LOGIN WINDOW");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        Escritorio = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        opLogin = new javax.swing.JButton();

        jDialog1.setTitle("ADVERTENCIA");
        jDialog1.setAutoRequestFocus(false);

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Escritorio.setBackground(java.awt.SystemColor.activeCaption);

        jLabel1.setText("User:");

        jLabel2.setText("Password:");

        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyPressed(evt);
            }
        });

        opLogin.setText("LOGIN");
        opLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opLoginActionPerformed(evt);
            }
        });

        Escritorio.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Escritorio.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Escritorio.setLayer(jTextField1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Escritorio.setLayer(jPasswordField1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Escritorio.setLayer(opLogin, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EscritorioLayout.createSequentialGroup()
                .addGroup(EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EscritorioLayout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addGroup(EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(33, 33, 33)
                        .addGroup(EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                            .addComponent(jTextField1)))
                    .addGroup(EscritorioLayout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(opLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(169, Short.MAX_VALUE))
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EscritorioLayout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addGroup(EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(opLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opLoginActionPerformed
        // TODO add your handling code here:
        // Declaración de las variables para la Base de Datos
        Connection cn;
        Statement s;
        ResultSet rst;
        System.out.println( "Iniciando Logeo al Sistema," );
        // Se carga el driver JDBC-ODBC
        try {
        Class.forName( "com.mysql.jdbc.Driver" );
        } catch( ClassNotFoundException e ) {
        System.out.println( "No se pudo cargar el puente JDBC-ODBC." );
        return;
        }
        try {
            cn = DriverManager.getConnection(
            "jdbc:mysql://db4free.net:3306/kmijapp","jefe21054","operahotspring123" );
            s = cn.createStatement();
            // verificar usuario es "S" o "N" en la BD
            /////////////////////////////
            String usuario1 = jTextField1.getText();
            String clave1 = String.valueOf(jPasswordField1.getPassword());
            String consulta_per1;     
            String permiso = "";
            consulta_per1 = "SELECT user, clave FROM USUARIO "
            + "WHERE user = '" + usuario1;
            consulta_per1 += "'AND clave = '" + clave1 + "'";
            rst = s.executeQuery( consulta_per1 );
            // Leer el resultado de la consulta
            while( rst.next() ) {
                permiso = rst.getString(1);
            }
            rst.close();
            /////////////////////////////
            
            if( !permiso.equals("") ){ //VERIFICA CUANDO ES NULO EN LA BASE DE DATOS
                if( ( permiso.equals( "admin" ) && permiso.equals( "admin" ) ) ){
                    this.dispose();
                    new Principal().setVisible(true);
                }
                    
                else{
                    this.dispose();
                    new PrincipalC().setVisible(true);    
                }
            }else{
                JOptionPane.showMessageDialog(null,"Ingrese como un usuario válido!");
                this.dispose();
                new Login().setVisible(true);
            }
            s.close();
            cn.close();
        }catch( SQLException e ) {
        System.out.println(e);
        // Pone los valores de las Cajas de Texto en nulo
        jTextField1.setText("");
        jPasswordField1.setText("");
        }
    }//GEN-LAST:event_opLoginActionPerformed

    private void jPasswordField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
           // Declaración de las variables para la Base de Datos
            Connection cn;
            Statement s;
            ResultSet rst;
            System.out.println( "Iniciando Logeo al Sistema," );
            // Se carga el driver JDBC-ODBC
            try {
            Class.forName( "com.mysql.jdbc.Driver" );
            } catch( ClassNotFoundException e ) {
            System.out.println( "No se pudo cargar el puente JDBC-ODBC." );
            return;
            }
            try {
                cn = DriverManager.getConnection(
                "jdbc:mysql://db4free.net:3306/kmijapp","jefe21054","operahotspring123" );
                s = cn.createStatement();
                // verificar usuario es "S" o "N" en la BD
                /////////////////////////////
                String usuario1 = jTextField1.getText();
                String clave1 = String.valueOf(jPasswordField1.getPassword());
                String consulta_per1;     
                String permiso = "";
                consulta_per1 = "SELECT user, clave FROM USUARIO "
                + "WHERE user = '" + usuario1;
                consulta_per1 += "'AND clave = '" + clave1 + "'";
                rst = s.executeQuery( consulta_per1 );
                // Leer el resultado de la consulta
                while( rst.next() ) {
                    permiso = rst.getString(1);
                }
                rst.close();
                /////////////////////////////

                if( !permiso.equals("") ){ //VERIFICA CUANDO ES NULO EN LA BASE DE DATOS
                    if( ( permiso.equals( "admin" ) && permiso.equals( "admin" ) ) ){
                        this.dispose();
                        new Principal().setVisible(true);
                    }

                    else{
                        this.dispose();
                        new PrincipalC().setVisible(true);    
                    }
                }else{
                    JOptionPane.showMessageDialog(null,"Ingrese como un usuario válido!");
                    this.dispose();
                    new Login().setVisible(true);
                }
                s.close();
                cn.close();
            }catch( SQLException e ) {
            System.out.println(e);
            // Pone los valores de las Cajas de Texto en nulo
            jTextField1.setText("");
            jPasswordField1.setText("");
            }   
        }
    }//GEN-LAST:event_jPasswordField1KeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton opLogin;
    // End of variables declaration//GEN-END:variables
}
