/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ivan
 */

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class Modificar extends javax.swing.JInternalFrame {

    /**
     * Creates new form Modificar
     */
    public Modificar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        opModificar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        opConsultaModifica = new javax.swing.JButton();

        jLabel3.setText("Nombre");

        opModificar.setText("MODIFICAR");
        opModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opModificarActionPerformed(evt);
            }
        });

        jLabel4.setText("Tipo Usuario");

        jLabel5.setText("Servicio");

        jLabel6.setText("Clave");

        jLabel2.setText("ID");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MODIFICAR DATOS");

        jTextField6.setEditable(false);

        opConsultaModifica.setText("CONSULTAR");
        opConsultaModifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opConsultaModificaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(107, 107, 107)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1)
                            .addComponent(jTextField2)
                            .addComponent(jTextField3)
                            .addComponent(jTextField4)
                            .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(opConsultaModifica)
                        .addGap(37, 37, 37)
                        .addComponent(opModificar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(570, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opConsultaModifica)
                    .addComponent(opModificar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(268, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opModificarActionPerformed
        // TODO add your handling code here:
        
        // Declaración de las variables para la Base de Datos
        Connection conexion;
        Statement sentencia;
        System.out.println( "Iniciando opcion de modificacion." );
        // Se carga el driver JDBC-ODBC
        try {
        Class.forName( "com.mysql.jdbc.Driver" );
        } catch( ClassNotFoundException e ) {
        System.out.println( "No se pudo cargar el puente JDBC-ODBC." );
        return;
        }
        try {
        // Borra valor de la Cajas de Texto comentario
        jTextField6.setText("");
        // Se establece la conexión con la base de datos
        conexion = DriverManager.getConnection(
        "jdbc:mysql://db4free.net:3306/kmijapp","jefe21054","operahotspring123" );
        sentencia = conexion.createStatement();
        // Toma los valores de las Cajas de Texto
        String usuarioTxt = jTextField1.getText();
        String nombreTxt = jTextField2.getText();
        String empresaTxt = jTextField3.getText();
        String admitirEnvioTxt = jTextField4.getText();
        String claveTxt = jTextField5.getText();
        // Modifica la Información de los usuarios
        int resulta = sentencia.executeUpdate("UPDATE USUARIO SET" +
        " user = '" + nombreTxt + "' ," +
        " TIPO_USUARIO_tipoUsuario = '" + empresaTxt + "' ," +
        " servicio = '" + admitirEnvioTxt + "' ," +
        " clave = '" + claveTxt + "' " +
        "WHERE id LIKE '" + usuarioTxt + "'");
        if( resulta != 0 ){
            JOptionPane.showMessageDialog(null,"Éxito en Operación!");
            jTextField6.setText("Modificación Correcta");
        }else{
            JOptionPane.showMessageDialog(null,"Fallo en Operación!");
            jTextField6.setText("No existe usuario");
        }
        conexion.close();
        } catch( SQLException e ) {
        System.out.println( e );
        return;
        }
        //Habilita caja de texo de nombre
        jTextField1.setEnabled(true);
        // Pone los valores de las Cajas de Texto en nulo
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
    }//GEN-LAST:event_opModificarActionPerformed

    private void opConsultaModificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opConsultaModificaActionPerformed
        // TODO add your handling code here:
        
        // Declaración de las variables para la Base de Datos
        Connection conexion;
        Statement sentencia;
        ResultSet resultado;
        System.out.println( "Iniciando opcion de consulta." );
        // Se carga el driver JDBC-ODBC
        try {
        Class.forName( "com.mysql.jdbc.Driver" );
        } catch( ClassNotFoundException e ) {
        System.out.println( "No se pudo cargar el puente JDBC-ODBC." );
        return;
        }
        try {
        // Ingresa la nombre para eliminar
        String usuarioTxt = jTextField1.getText();
        // Se establece la conexión con la base de datos
        conexion = DriverManager.getConnection(
        "jdbc:mysql://db4free.net:3306/kmijapp","jefe21054","operahotspring123"  );
        sentencia = conexion.createStatement();
        // Se realiza la consulta de la tabla USUARIOS
        resultado = sentencia.executeQuery( "SELECT * FROM USUARIO" +
        " WHERE id LIKE '" + usuarioTxt + "'");
        // Muestra los valores de las Cajas de Texto
        resultado.first();
        jTextField2.setText(resultado.getString("user"));
        jTextField3.setText(resultado.getString("TIPO_USUARIO_tipoUsuario"));
        jTextField4.setText(resultado.getString("servicio"));
        jTextField5.setText(resultado.getString("clave"));
        // Desabilita caja de texo de nombre
        jTextField1.setEnabled(false);
        conexion.close();
        } catch( SQLException e ) {
        System.out.println( e );
        JOptionPane.showMessageDialog(null,"Fallo en Operación!");
        jTextField6.setText("No existe el usuario");
        }
    }//GEN-LAST:event_opConsultaModificaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JButton opConsultaModifica;
    private javax.swing.JButton opModificar;
    // End of variables declaration//GEN-END:variables
}
