
import java.beans.PropertyVetoException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ivan
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        // JFrame adquiriendo el tamaño de pantalla completa o FullScreen
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setTitle("KMIJ APLICACION ADMINISTRADOR");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")       
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        opSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        opConsultar = new javax.swing.JMenuItem();
        opIngresar = new javax.swing.JMenuItem();
        opBorrar = new javax.swing.JMenuItem();
        opModificar = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        opConsultarUsuarios = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 854, Short.MAX_VALUE)
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 491, Short.MAX_VALUE)
        );

        jMenu1.setText("Archivo");

        opSalir.setText("Salir");
        opSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opSalirActionPerformed(evt);
            }
        });
        jMenu1.add(opSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Mantenimiento");

        opConsultar.setText("Consultar");
        opConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opConsultarActionPerformed(evt);
            }
        });
        jMenu2.add(opConsultar);

        opIngresar.setText("Ingresar");
        opIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opIngresarActionPerformed(evt);
            }
        });
        jMenu2.add(opIngresar);

        opBorrar.setText("Borrar");
        opBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opBorrarActionPerformed(evt);
            }
        });
        jMenu2.add(opBorrar);

        opModificar.setText("Modificar");
        opModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opModificarActionPerformed(evt);
            }
        });
        jMenu2.add(opModificar);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("ConsultaTotal");

        opConsultarUsuarios.setText("Consulta");
        opConsultarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opConsultarUsuariosActionPerformed(evt);
            }
        });
        jMenu3.add(opConsultarUsuarios);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_opSalirActionPerformed

    private void opConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opConsultarActionPerformed
        // TODO add your handling code here:
        Consultar ConsultarUsuario = new Consultar();
        Escritorio.add(ConsultarUsuario);
        ConsultarUsuario.show();
        // JInternalFrame Maximizado en la pantalla completa o FullScreen
        try {
            ConsultarUsuario.setMaximum(true);
        } catch(PropertyVetoException e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_opConsultarActionPerformed

    private void opIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opIngresarActionPerformed
        // TODO add your handling code here:
        Ingresar IngresarUsuario = new Ingresar();
        Escritorio.add(IngresarUsuario);
        IngresarUsuario.show();
        // JInternalFrame Maximizado en la pantalla completa o FullScreen
        try {
            IngresarUsuario.setMaximum(true);
        } catch(PropertyVetoException e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_opIngresarActionPerformed

    private void opBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opBorrarActionPerformed
        // TODO add your handling code here:
        Borrar BorrarUsuario = new Borrar();
        Escritorio.add(BorrarUsuario);
        BorrarUsuario.show();
        // JInternalFrame Maximizado en la pantalla completa o FullScreen
        try {
            BorrarUsuario.setMaximum(true);
        } catch(PropertyVetoException e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_opBorrarActionPerformed

    private void opModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opModificarActionPerformed
        // TODO add your handling code here:
        Modificar ModificarUsuario = new Modificar();
        Escritorio.add(ModificarUsuario);
        ModificarUsuario.show();
        // JInternalFrame Maximizado en la pantalla completa o FullScreen
        try {
            ModificarUsuario.setMaximum(true);
        } catch(PropertyVetoException e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_opModificarActionPerformed

    private void opConsultarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opConsultarUsuariosActionPerformed
        // TODO add your handling code here:
        ConsultarUsuarios ConsultaTotal = new ConsultarUsuarios();
        Escritorio.add(ConsultaTotal);
        ConsultaTotal.show();
        // JInternalFrame Maximizado en la pantalla completa o FullScreen
        try {
            ConsultaTotal.setMaximum(true);
        } catch(PropertyVetoException e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_opConsultarUsuariosActionPerformed
        
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem opBorrar;
    private javax.swing.JMenuItem opConsultar;
    private javax.swing.JMenuItem opConsultarUsuarios;
    private javax.swing.JMenuItem opIngresar;
    private javax.swing.JMenuItem opModificar;
    private javax.swing.JMenuItem opSalir;
    // End of variables declaration//GEN-END:variables
}
